### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by vanillainanutshell** [mukhammadrizooff/Leaderboard#3]
# Your code is good so far, so to highlight:

- Send and receive data from an API. ✔️
- Use API documentation. ✔️
- Understand and use JSON. ✔️
- Make JavaScript code asynchronous. ✔️

<img src="https://media4.giphy.com/media/fT3PPZwB2lZMk/giphy.gif"/>

**Comment by memelopez** [comment]
nice work rizo!
